---  # Apache Jena & Fuseki triple store
version: '3'
services:
  graphdb:
    image: khaller/graphdb-free
    container_name: graphdb
    environment:
      - GDB_HEAP_SIZE=3g
    volumes:
      - ./graphdb/graphdb.properties:/opt/graphdb/conf/graphdb.properties
      - ./graphdb_data:/opt/graphdb/data/repositories
    ports:
      - 7200:7200
  pad_api:
    build:
      context: .
      dockerfile: ./pad_api/Dockerfile
    container_name: pad_api
    environment:
      - APP_ENVIRONMENT=production
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - APP_SPARQL_HOST=http://graphdb:7200
      - APP_SPARQL_QUERY_PATH=/repositories/pad
      - APP_GLOBAL_LIMIT=50
    ports:
      - 5001:5000
  job_api:
    build:
      context: .
      dockerfile: ./pad_api/Dockerfile
    container_name: job_api
    environment:
      - APP_ENVIRONMENT=production
      - APP_HOST=0.0.0.0
      - APP_PORT=5002
      - APP_SPARQL_HOST=http://graphdb:7200
      - APP_SPARQL_QUERY_PATH=/repositories/job
      - APP_GLOBAL_LIMIT=50
    ports:
      - 5002:5000
