import os

DEFAULT_GLOBAL_LIMIT = 50
DEFAULT_SPARQL_HOST = os.getenv('APP_SPARQL_HOST', "http://localhost:7200")
DEFAULT_SPARQL_QUERY_PATH = os.getenv('APP_SPARQL_QUERY_PATH', "/repositories/job")

SPARQL_HOST = os.getenv('APP_SPARQL_HOST', DEFAULT_SPARQL_HOST)
SPARQL_QUERY_PATH = os.getenv('APP_SPARQL_QUERY_PATH', DEFAULT_SPARQL_QUERY_PATH)
SPARQL_ENDPOINT = SPARQL_HOST + SPARQL_QUERY_PATH
GLOBAL_LIMIT = int(os.getenv('APP_GLOBAL_LIMIT', DEFAULT_GLOBAL_LIMIT))
